# https://eslint.org/docs/rules/
env:
  browser: true
  es6: false
  node: false
  jquery: true
globals:
  page_load: true
  page_unload: true
rules:
  no-console: 0
  comma-dangle:
    - warn
    - only-multiline
  indent:
    - error
    - 2
    - ignoreComments: true
  keyword-spacing:
    - error
    - after: true
      before: true
  linebreak-style:
    - error
    - unix
  no-trailing-spaces:
    - error
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  quotes:
    - error
    - single
  object-curly-spacing:
    - error
    - always
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - always
  max-len:
    - warn
    - 80
    - ignoreComments: true
      ignoreUrls: true
      ignorePattern: "\\s*<"
