:anime:
  - 111111111 # for test purposes
:manga:
  - 222222222 # for test purposes
:ranobe:
  - 333333333 # for test purposes
:character:
  - 444444444 # for test purposes
  - 39908 # Mayuge Nuribe (2)
  - 129705 # Mayuge (1)
:person:
  - 555555555 # for test purposes
